### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hoyer-a** [Microphone-Array-Project/ema2ambisonics#1]
# Checklist for code
Created an Issue to collect stuff and keep track of progress, todos etc. etc.

PR for radial filters: #2 

- [ ] Set up doxygen

**Utils**

- [x] Tikhonov regularization with a given maximum gain (#2)
- [x] Hard & Soft Limiting (#2)
- [x] Spherical Hankel Function (#2)
- [x] Spherical Hankel Derivative (#2)
- [ ] write Tests

**Radial Filters**
- [x] Implement radial filters (#2)
- [ ] Write functionality tests
- [x] Validate results (#2)

**SH soundfield coefficients**

- [ ]  [get_sound_field_sh_coeffs_from_ema_t](https://github.com/AppliedAcousticsChalmers/ambisonic-encoding/blob/main/dependencies/get_sound_field_sh_coeffs_from_ema_t.m) (#4)
- [ ] Validate Results (#4)

**Ema2Ambisonics**
[render_ema_to_ambisonics](https://github.com/AppliedAcousticsChalmers/ambisonic-encoding/blob/main/render_ema_to_ambisonics.m)
- Could be an example notebook

**Readme**

- [ ] Write readme with instructions on how to use the code
- [ ] Add example notebook
